---
- name: show memory-disk info
  hosts: local
  become: true
  tasks:
    - name: execute "free" command
      command: free -m
      register: free_output

    - name: print "free" ouput
      debug:
        var: free_output.stdout_lines

    - name: execute "df" command
      command: df -h
      register: df_output

    - name: print "df" ouput
      debug:
        var: df_output.stdout_lines
